### ISSUE TITLE
There is no MICRO schema

### ISSUE THREAD

**Issue by fatemeh-aghaei** [francescomucio/exasol-explain#1]
I ran these scripts but it can not open micro schema. can you please give more details . thanks

**Comment by francescomucio** [comment]
sorry about that (a colleague mentioned this problem to me and I knew one day someone would have this problem).

Micro is the schema I used in my work environment, replace it with then name of the schema where you deployed these script or just remove it, if you use only one schema. 

That way it should work.

**Comment by fatemeh-aghaei** [comment]
Thanks I realised that. I have a sql script consisting of several queries and I want to run the whole script and see the query plan. Is there any way to do that? while with explain is not working. thanks.

**Comment by francescomucio** [comment]
You cannot do this with the script or, maybe, you can do it.

1. One way to do is to enable the profiling as explained in the EXASOL manual, run your queries and the check the results in the profiling table.

2. Another way is to enable my profiling script, put explain in front of all your queries and then check the profiling table.

In both cases, if you have the session_id and statement_id of your queries you can use explain_this() to see the plan of each single query.

Does this make sense?
